<?php
// This file is generated by build/generateAutoload.php, do not adjust manually
// phpcs:disable Generic.Files.LineLength
global $wgAutoloadClasses;

$wgAutoloadClasses += [
	'Wikibase\\ClientHooks' => __DIR__ . '/ClientHooks.php',
	'Wikibase\\PopulateEntityUsage' => __DIR__ . '/maintenance/populateEntityUsage.php',
	'Wikibase\\PopulateInterwiki' => __DIR__ . '/maintenance/populateInterwiki.php',
	'Wikibase\\UpdateSubscriptions' => __DIR__ . '/maintenance/updateSubscriptions.php',
];
