-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/Wikibase/repo/sql/abstractSchemaChanges/patch-wb_changes_dispatch-make-chd_seen-unsigned.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  /*_*/wb_changes_dispatch
CHANGE  chd_seen chd_seen INT UNSIGNED DEFAULT 0 NOT NULL;