# See https://www.mediawiki.org/wiki/Manual:Coding_conventions/Ruby
inherit_from: .rubocop_todo.yml

AllCops:
  StyleGuideCopsOnly: true

Metrics/MethodLength:
  Enabled: false

Style/Alias:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/TrivialAccessors:
  ExactNameMatch: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/AsciiComments:
  Enabled: false
