#ruby=ruby-2.0.0-p247
#ruby-gemset=Wikibase-selenium_cuc

source 'https://rubygems.org'

gem 'page-object'
gem 'require_all'
gem 'rspec-expectations'
gem 'syntax'
gem 'cucumber'
gem 'json'
gem 'activesupport'
gem 'net-http-persistent'
