<?php
// This file is generated by build/generateAutoload.php, do not adjust manually
// phpcs:disable Generic.Files.LineLength
global $wgAutoloadClasses;

$wgAutoloadClasses += [
	'Wikibase\\Repo\\Maintenance\\AddUnitConversions' => __DIR__ . '/maintenance/addUnitConversions.php',
	'Wikibase\\Repo\\Maintenance\\ChangePropertyDataType' => __DIR__ . '/maintenance/changePropertyDataType.php',
	'Wikibase\\Repo\\Maintenance\\ClearTermSqlIndexSearchFields' => __DIR__ . '/maintenance/clearTermSqlIndexSearchFields.php',
	'Wikibase\\Repo\\Maintenance\\DispatchChanges' => __DIR__ . '/maintenance/dispatchChanges.php',
	'Wikibase\\Repo\\Maintenance\\DumpJson' => __DIR__ . '/maintenance/dumpJson.php',
	'Wikibase\\Repo\\Maintenance\\DumpRdf' => __DIR__ . '/maintenance/dumpRdf.php',
	'Wikibase\\Repo\\Maintenance\\PopulateChangesSubscription' => __DIR__ . '/maintenance/populateChangesSubscription.php',
	'Wikibase\\Repo\\Maintenance\\PopulateTermFullEntityId' => __DIR__ . '/maintenance/populateTermFullEntityId.php',
	'Wikibase\\Repo\\Maintenance\\PopulateWithRandomEntitiesAndTerms' => __DIR__ . '/maintenance/populateWithRandomEntitiesAndTerms.php',
	'Wikibase\\Repo\\Maintenance\\PruneChanges' => __DIR__ . '/maintenance/pruneChanges.php',
	'Wikibase\\Repo\\Maintenance\\PruneItemsPerSite' => __DIR__ . '/maintenance/pruneItemsPerSite.php',
	'Wikibase\\Repo\\Maintenance\\RebuildItemTerms' => __DIR__ . '/maintenance/rebuildItemTerms.php',
	'Wikibase\\Repo\\Maintenance\\RebuildItemsPerSite' => __DIR__ . '/maintenance/rebuildItemsPerSite.php',
	'Wikibase\\Repo\\Maintenance\\RebuildPropertyInfo' => __DIR__ . '/maintenance/rebuildPropertyInfo.php',
	'Wikibase\\Repo\\Maintenance\\RebuildPropertyTerms' => __DIR__ . '/maintenance/rebuildPropertyTerms.php',
	'Wikibase\\Repo\\Maintenance\\RebuildTermSqlIndex' => __DIR__ . '/maintenance/rebuildTermSqlIndex.php',
	'Wikibase\\Repo\\Maintenance\\RebuildTermsSearchKey' => __DIR__ . '/maintenance/rebuildTermsSearchKey.php',
	'Wikibase\\Repo\\Maintenance\\RemoveTermsInLanguage' => __DIR__ . '/maintenance/removeTermsInLanguage.php',
	'Wikibase\\Repo\\Maintenance\\SearchEntities' => __DIR__ . '/maintenance/searchEntities.php',
	'Wikibase\\Repo\\Maintenance\\UpdateUnits' => __DIR__ . '/maintenance/updateUnits.php',
];
