-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Wikibase/client/sql/abstract/entity_usage.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wbc_entity_usage (
  eu_row_id BIGINT AUTO_INCREMENT NOT NULL,
  eu_entity_id VARBINARY(255) NOT NULL,
  eu_aspect VARBINARY(37) NOT NULL,
  eu_page_id INT NOT NULL,
  UNIQUE INDEX eu_entity_id (
    eu_entity_id, eu_aspect, eu_page_id
  ),
  INDEX eu_page_id (eu_page_id, eu_entity_id),
  PRIMARY KEY(eu_row_id)
) /*$wgDBTableOptions*/;
