<?php
// This file is generated by build/generateAutoload.php, do not adjust manually
// @codingStandardsIgnoreFile
global $wgAutoloadClasses;

$wgAutoloadClasses += [
	'Wikibase\\DataAccess\\DataAccessServices' => __DIR__ . '/src/DataAccessServices.php',
	'Wikibase\\DataAccess\\DataAccessSettings' => __DIR__ . '/src/DataAccessSettings.php',
	'Wikibase\\DataAccess\\GenericServices' => __DIR__ . '/src/GenericServices.php',
	'Wikibase\\DataAccess\\MultiRepositoryServices' => __DIR__ . '/src/MultiRepositoryServices.php',
	'Wikibase\\DataAccess\\MultipleRepositoryAwareWikibaseServices' => __DIR__ . '/src/MultipleRepositoryAwareWikibaseServices.php',
	'Wikibase\\DataAccess\\PerRepositoryServiceContainer' => __DIR__ . '/src/PerRepositoryServiceContainer.php',
	'Wikibase\\DataAccess\\PerRepositoryServiceContainerFactory' => __DIR__ . '/src/PerRepositoryServiceContainerFactory.php',
	'Wikibase\\DataAccess\\Serializer\\ForbiddenSerializer' => __DIR__ . '/src/Serializer/ForbiddenSerializer.php',
	'Wikibase\\DataAccess\\WikibaseServices' => __DIR__ . '/src/WikibaseServices.php',
];
