<?php
// This file is generated by build/generateAutoload.php, do not adjust manually
// phpcs:disable Generic.Files.LineLength
global $wgAutoloadClasses;

$wgAutoloadClasses += [
	'Wikibase\\DataAccess\\ByTypeDispatchingEntityInfoBuilder' => __DIR__ . '/src/ByTypeDispatchingEntityInfoBuilder.php',
	'Wikibase\\DataAccess\\ByTypeDispatchingEntityPrefetcher' => __DIR__ . '/src/ByTypeDispatchingEntityPrefetcher.php',
	'Wikibase\\DataAccess\\ByTypeDispatchingEntityRevisionLookup' => __DIR__ . '/src/ByTypeDispatchingEntityRevisionLookup.php',
	'Wikibase\\DataAccess\\ByTypeDispatchingPrefetchingTermLookup' => __DIR__ . '/src/ByTypeDispatchingPrefetchingTermLookup.php',
	'Wikibase\\DataAccess\\DataAccessServices' => __DIR__ . '/src/DataAccessServices.php',
	'Wikibase\\DataAccess\\DataAccessSettings' => __DIR__ . '/src/DataAccessSettings.php',
	'Wikibase\\DataAccess\\EntitySource' => __DIR__ . '/src/EntitySource.php',
	'Wikibase\\DataAccess\\EntitySourceDefinitions' => __DIR__ . '/src/EntitySourceDefinitions.php',
	'Wikibase\\DataAccess\\EntitySourceDefinitionsConfigParser' => __DIR__ . '/src/EntitySourceDefinitionsConfigParser.php',
	'Wikibase\\DataAccess\\GenericServices' => __DIR__ . '/src/GenericServices.php',
	'Wikibase\\DataAccess\\MediaWiki\\EntitySourceDocumentUrlProvider' => __DIR__ . '/src/MediaWiki/EntitySourceDocumentUrlProvider.php',
	'Wikibase\\DataAccess\\MultiRepositoryServices' => __DIR__ . '/src/MultiRepositoryServices.php',
	'Wikibase\\DataAccess\\MultipleEntitySourceServices' => __DIR__ . '/src/MultipleEntitySourceServices.php',
	'Wikibase\\DataAccess\\MultipleRepositoryAwareWikibaseServices' => __DIR__ . '/src/MultipleRepositoryAwareWikibaseServices.php',
	'Wikibase\\DataAccess\\PerRepositoryServiceContainer' => __DIR__ . '/src/PerRepositoryServiceContainer.php',
	'Wikibase\\DataAccess\\PerRepositoryServiceContainerFactory' => __DIR__ . '/src/PerRepositoryServiceContainerFactory.php',
	'Wikibase\\DataAccess\\Serializer\\ForbiddenSerializer' => __DIR__ . '/src/Serializer/ForbiddenSerializer.php',
	'Wikibase\\DataAccess\\SingleEntitySourceServices' => __DIR__ . '/src/SingleEntitySourceServices.php',
	'Wikibase\\DataAccess\\Tests\\DataAccessSettingsFactory' => __DIR__ . '/tests/phpunit/DataAccessSettingsFactory.php',
	'Wikibase\\DataAccess\\Tests\\EntityPrefetcherSpy' => __DIR__ . '/tests/phpunit/EntityPrefetcherSpy.php',
	'Wikibase\\DataAccess\\Tests\\FakePrefetchingTermLookup' => __DIR__ . '/tests/phpunit/FakePrefetchingTermLookup.php',
	'Wikibase\\DataAccess\\UnusableEntitySource' => __DIR__ . '/src/UnusableEntitySource.php',
	'Wikibase\\DataAccess\\WikibaseServices' => __DIR__ . '/src/WikibaseServices.php',
];
