-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Wikibase/repo/sql/abstract/wb_changes.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wb_changes (
  change_id SERIAL NOT NULL,
  change_type VARCHAR(25) NOT NULL,
  change_time TIMESTAMPTZ NOT NULL,
  change_object_id TEXT NOT NULL,
  change_revision_id INT NOT NULL,
  change_user_id INT NOT NULL,
  change_info TEXT NOT NULL,
  PRIMARY KEY(change_id)
);

CREATE INDEX wb_changes_change_time ON wb_changes (change_time);

CREATE INDEX wb_changes_change_revision_id ON wb_changes (change_revision_id);

CREATE INDEX change_object_id ON wb_changes (change_object_id);
