-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/Wikibase/repo/sql/abstractSchemaChanges/patch-wb_changes_dispatch-make-chd_seen-unsigned.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX wb_changes_dispatch_chd_seen;
DROP  INDEX wb_changes_dispatch_chd_touched;
CREATE TEMPORARY TABLE /*_*/__temp__wb_changes_dispatch AS
SELECT  chd_site,  chd_db,  chd_seen,  chd_touched,  chd_lock,  chd_disabled
FROM  /*_*/wb_changes_dispatch;
DROP  TABLE  /*_*/wb_changes_dispatch;
CREATE TABLE  /*_*/wb_changes_dispatch (    chd_site BLOB NOT NULL,    chd_db BLOB NOT NULL,    chd_touched BLOB DEFAULT '00000000000000' NOT NULL,    chd_lock BLOB DEFAULT NULL,    chd_disabled SMALLINT UNSIGNED DEFAULT 0 NOT NULL,    chd_seen INTEGER UNSIGNED DEFAULT 0 NOT NULL,    PRIMARY KEY(chd_site)  );
INSERT INTO  /*_*/wb_changes_dispatch (    chd_site, chd_db, chd_seen, chd_touched,    chd_lock, chd_disabled  )
SELECT  chd_site,  chd_db,  chd_seen,  chd_touched,  chd_lock,  chd_disabled
FROM  /*_*/__temp__wb_changes_dispatch;
DROP  TABLE /*_*/__temp__wb_changes_dispatch;
CREATE INDEX wb_changes_dispatch_chd_seen ON  /*_*/wb_changes_dispatch (chd_seen);
CREATE INDEX wb_changes_dispatch_chd_touched ON  /*_*/wb_changes_dispatch (chd_touched);