-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Wikibase/repo/sql/abstract/wb_changes_dispatch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wb_changes_dispatch (
  chd_site VARBINARY(32) NOT NULL,
  chd_db VARBINARY(32) NOT NULL,
  chd_seen INT UNSIGNED DEFAULT 0 NOT NULL,
  chd_touched VARBINARY(14) DEFAULT '00000000000000' NOT NULL,
  chd_lock VARBINARY(64) DEFAULT NULL,
  chd_disabled TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  INDEX wb_changes_dispatch_chd_seen (chd_seen),
  INDEX wb_changes_dispatch_chd_touched (chd_touched),
  PRIMARY KEY(chd_site)
) /*$wgDBTableOptions*/;
