-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Wikibase/repo/sql/abstract/wb_items_per_site.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wb_items_per_site (
  ips_row_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  ips_item_id INT UNSIGNED NOT NULL,
  ips_site_id VARBINARY(32) NOT NULL,
  ips_site_page VARCHAR(310) NOT NULL,
  UNIQUE INDEX wb_ips_item_site_page (ips_site_id, ips_site_page),
  INDEX wb_ips_item_id (ips_item_id),
  PRIMARY KEY(ips_row_id)
) /*$wgDBTableOptions*/;
