-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: repo/sql/abstract/wb_remote_entity.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wb_remote_entity (
  re_repository VARCHAR(32) NOT NULL,
  re_entity_id VARCHAR(64) NOT NULL,
  re_touched BINARY(14) NOT NULL,
  re_blob MEDIUMBLOB NOT NULL,
  INDEX wb_remote_entity_touched (re_touched),
  PRIMARY KEY(re_repository, re_entity_id)
) /*$wgDBTableOptions*/;
