-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Wikibase/repo/sql/abstract/wb_changes.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wb_changes (
  change_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  change_type VARCHAR(25) NOT NULL,
  change_time BLOB NOT NULL,
  change_object_id BLOB NOT NULL,
  change_revision_id INTEGER UNSIGNED NOT NULL,
  change_user_id INTEGER UNSIGNED NOT NULL,
  change_info BLOB NOT NULL
);

CREATE INDEX wb_changes_change_time ON /*_*/wb_changes (change_time);

CREATE INDEX wb_changes_change_revision_id ON /*_*/wb_changes (change_revision_id);

CREATE INDEX change_object_id ON /*_*/wb_changes (change_object_id);
