-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Wikibase/repo/sql/abstract/wb_changes_dispatch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wb_changes_dispatch (
  chd_site BLOB NOT NULL,
  chd_db BLOB NOT NULL,
  chd_seen INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  chd_touched BLOB DEFAULT '00000000000000' NOT NULL,
  chd_lock BLOB DEFAULT NULL,
  chd_disabled SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
  PRIMARY KEY(chd_site)
);

CREATE INDEX wb_changes_dispatch_chd_seen ON /*_*/wb_changes_dispatch (chd_seen);

CREATE INDEX wb_changes_dispatch_chd_touched ON /*_*/wb_changes_dispatch (chd_touched);
