-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: repo/sql/abstract/wb_remote_entity.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wb_remote_entity (
  re_concept_uri VARCHAR(512) NOT NULL,
  re_touched BLOB NOT NULL,
  re_blob BLOB NOT NULL,
  PRIMARY KEY(re_concept_uri)
);

CREATE INDEX wb_remote_entity_touched ON /*_*/wb_remote_entity (re_touched);
