-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Wikibase/client/sql/abstract/entity_usage.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wbc_entity_usage (
  eu_row_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  eu_entity_id BLOB NOT NULL, eu_aspect BLOB NOT NULL,
  eu_page_id INTEGER NOT NULL
);

CREATE UNIQUE INDEX eu_entity_id ON /*_*/wbc_entity_usage (
  eu_entity_id, eu_aspect, eu_page_id
);

CREATE INDEX eu_page_id ON /*_*/wbc_entity_usage (eu_page_id, eu_entity_id);
