<?php

/**
 * @license GPL-2.0-or-later
 * @author Adrian Heine <adrian.heine@wikimedia.de>
 */

return [
	'wikibase.tests' => [
		'localBasePath' => __DIR__,
		'remoteExtPath' => 'Wikibase/view/tests/qunit',
		'scripts' => [
			'getMockListItemAdapter.js',
		],
		'dependencies' => [
			'wikibase.tests',
		]
	],
	'wikibase.experts.tests' => [
		'localBasePath' => __DIR__ . '/experts',
		'remoteExtPath' => 'Wikibase/view/tests/qunit/experts',
		'scripts' => [
			'wikibase.experts.modules.tests.js',
		],
		'dependencies' => [
			'wikibase.experts.modules',
		],
	],
	'wikibase.jquery.tests' => [
		'localBasePath' => __DIR__ . '/jquery',
		'remoteExtPath' => 'Wikibase/view/tests/qunit/jquery',
		'scripts' => [
			'ui/jquery.ui.closeable.tests.js',
			'ui/jquery.ui.tagadata.tests.js',
			'ui/jquery.ui.EditableTemplatedWidget.tests.js',
			'ui/jquery.ui.TemplatedWidget.tests.js',
			'wikibase/snakview/snakview.tests.js',
			'wikibase/toolbar/jquery.wikibase.addtoolbar.tests.js',
			'wikibase/toolbar/jquery.wikibase.edittoolbar.tests.js',
			'wikibase/toolbar/jquery.wikibase.removetoolbar.tests.js',
			'wikibase/toolbar/jquery.wikibase.singlebuttontoolbar.tests.js',
			'wikibase/toolbar/jquery.wikibase.toolbar.tests.js',
			'wikibase/toolbar/jquery.wikibase.toolbarbutton.tests.js',
			'wikibase/toolbar/jquery.wikibase.toolbaritem.tests.js',
			'wikibase/jquery.wikibase.aliasesview.tests.js',
			'wikibase/jquery.wikibase.badgeselector.tests.js',
			'wikibase/jquery.wikibase.statementgrouplabelscroll.tests.js',
			'wikibase/jquery.wikibase.statementgrouplistview.tests.js',
			'wikibase/jquery.wikibase.statementgroupview.tests.js',
			'wikibase/jquery.wikibase.statementlistview.tests.js',
			'wikibase/jquery.wikibase.descriptionview.tests.js',
			'wikibase/jquery.wikibase.entityselector.tests.js',
			'wikibase/jquery.wikibase.entityview.tests.js',
			'wikibase/jquery.wikibase.entitytermsview.tests.js',
			'wikibase/jquery.wikibase.entitytermsforlanguagelistview.tests.js',
			'wikibase/jquery.wikibase.entitytermsforlanguageview.tests.js',
			'wikibase/jquery.wikibase.itemview.tests.js',
			'wikibase/jquery.wikibase.labelview.tests.js',
			'wikibase/jquery.wikibase.listview.tests.js',
			'wikibase/jquery.wikibase.pagesuggester.tests.js',
			'wikibase/jquery.wikibase.propertyview.tests.js',
			'wikibase/jquery.wikibase.referenceview.tests.js',
			'wikibase/jquery.wikibase.sitelinkgrouplistview.tests.js',
			'wikibase/jquery.wikibase.sitelinkgroupview.tests.js',
			'wikibase/jquery.wikibase.sitelinklistview.tests.js',
			'wikibase/jquery.wikibase.sitelinkview.tests.js',
			'wikibase/jquery.wikibase.snaklistview.tests.js',
			'wikibase/jquery.wikibase.statementview.RankSelector.tests.js',
			'wikibase/jquery.wikibase.statementview.tests.js',
			'jquery.removeClassByRegex.tests.js',
			'jquery.sticknode.tests.js',
			'jquery.util.EventSingletonManager.tests.js',
			'jquery.util.getDirectionality.tests.js',
		],
		'dependencies' => [
			'dataValues.values',
			'jquery.removeClassByRegex',
			'jquery.sticknode',
			'jquery.ui.closeable',
			'jquery.ui.EditableTemplatedWidget',
			'jquery.ui.tagadata',
			'jquery.ui.TemplatedWidget',
			'jquery.util.EventSingletonManager',
			'jquery.util.getDirectionality',
			'jquery.wikibase.addtoolbar',
			'jquery.wikibase.aliasesview',
			'jquery.wikibase.badgeselector',
			'jquery.wikibase.descriptionview',
			'jquery.wikibase.edittoolbar',
			'jquery.wikibase.entityselector',
			'jquery.wikibase.entitytermsforlanguagelistview',
			'jquery.wikibase.entitytermsforlanguageview',
			'jquery.wikibase.entitytermsview',
			'jquery.wikibase.entityview',
			'jquery.wikibase.itemview',
			'jquery.wikibase.labelview',
			'jquery.wikibase.listview',
			'jquery.wikibase.pagesuggester',
			'jquery.wikibase.propertyview',
			'jquery.wikibase.referenceview',
			'jquery.wikibase.removetoolbar',
			'jquery.wikibase.singlebuttontoolbar',
			'jquery.wikibase.sitelinkgrouplistview',
			'jquery.wikibase.sitelinkgroupview',
			'jquery.wikibase.sitelinklistview',
			'jquery.wikibase.sitelinkview',
			'jquery.wikibase.snaklistview',
			'jquery.wikibase.snakview',
			'jquery.wikibase.statementgrouplabelscroll',
			'jquery.wikibase.statementgrouplistview',
			'jquery.wikibase.statementgroupview',
			'jquery.wikibase.statementlistview',
			'jquery.wikibase.statementview',
			'jquery.wikibase.toolbar',
			'jquery.wikibase.toolbarbutton',
			'jquery.wikibase.toolbaritem',
			'test.sinonjs',
			'wikibase.datamodel.Claim',
			'wikibase.datamodel.Item',
			'wikibase.datamodel.MultiTerm',
			'wikibase.datamodel.Property',
			'wikibase.datamodel.PropertyNoValueSnak',
			'wikibase.datamodel.PropertySomeValueSnak',
			'wikibase.datamodel.PropertyValueSnak',
			'wikibase.datamodel.Reference',
			'wikibase.datamodel.ReferenceList',
			'wikibase.datamodel.SiteLink',
			'wikibase.datamodel.SiteLinkSet',
			'wikibase.datamodel.SnakList',
			'wikibase.datamodel.Statement',
			'wikibase.datamodel.StatementGroup',
			'wikibase.datamodel.StatementGroupSet',
			'wikibase.datamodel.StatementList',
			'wikibase.datamodel.Term',
			'wikibase.datamodel',
			'wikibase.serialization.SnakDeserializer',
			'wikibase.serialization.SnakSerializer',
			'wikibase.store.EntityStore',
			'wikibase.templates',
			'wikibase.tests',
			'wikibase.tests.qunit.testrunner',
		],
	],
	'wikibase.wikibase.tests' => [
		'localBasePath' => __DIR__ . '/wikibase',
		'remoteExtPath' => 'Wikibase/view/tests/qunit/wikibase',
		'scripts' => [
			'entityChangers/AliasesChanger.tests.js',
			'entityChangers/StatementsChanger.tests.js',
			'entityChangers/DescriptionsChanger.tests.js',
			'entityChangers/EntityTermsChanger.tests.js',
			'entityChangers/LabelsChanger.tests.js',
			'entityChangers/SiteLinksChanger.tests.js',
			'entityChangers/SiteLinkSetsChanger.tests.js',
			'entityIdFormatter/testEntityIdHtmlFormatter.js',
			'entityIdFormatter/DataValueBasedEntityIdHtmlFormatter.tests.js',
			'entityIdFormatter/DataValueBasedEntityIdPlainFormatter.tests.js',
			'store/store.CachingEntityStore.tests.js',
			'store/store.CombiningEntityStore.tests.js',
			'utilities/ClaimGuidGenerator.tests.js',
			'utilities/GuidGenerator.tests.js',
			'view/testViewController.js',
			'view/ToolbarViewController.tests.js',
			'view/ViewFactory.tests.js',
			'view/ViewFactoryFactory.tests.js',
			'view/ToolbarFactory.tests.js',
			'wikibase.WikibaseContentLanguages.tests.js',
			'wikibase.getLanguageNameByCode.tests.js',
			'templates.tests.js',
			'wikibase.ValueViewBuilder.tests.js',
		],
		'dependencies' => [
			'test.sinonjs',
			'wikibase.datamodel.Claim',
			'wikibase.datamodel.EntityId',
			'wikibase.datamodel.Fingerprint',
			'wikibase.datamodel.Item',
			'wikibase.datamodel.PropertyNoValueSnak',
			'wikibase.datamodel.Statement',
			'wikibase.datamodel.StatementGroup',
			'wikibase.datamodel.StatementList',
			'wikibase.datamodel',
			'wikibase.entityChangers.AliasesChanger',
			'wikibase.entityChangers.DescriptionsChanger',
			'wikibase.entityChangers.EntityTermsChanger',
			'wikibase.entityChangers.LabelsChanger',
			'wikibase.entityChangers.SiteLinksChanger',
			'wikibase.entityChangers.SiteLinkSetsChanger',
			'wikibase.entityChangers.StatementsChanger',
			'wikibase.entityIdFormatter.__namespace',
			'wikibase.entityIdFormatter.DataValueBasedEntityIdHtmlFormatter',
			'wikibase.entityIdFormatter.DataValueBasedEntityIdPlainFormatter',
			'wikibase.entityIdFormatter.EntityIdHtmlFormatter',
			'wikibase.entityIdFormatter.EntityIdPlainFormatter',
			'wikibase.getLanguageNameByCode',
			'wikibase.serialization.StatementDeserializer',
			'wikibase.serialization.StatementSerializer',
			'wikibase.store.CachingEntityStore',
			'wikibase.store.CombiningEntityStore',
			'wikibase.store.EntityStore',
			'wikibase.templates',
			'wikibase.utilities.ClaimGuidGenerator',
			'wikibase.utilities.GuidGenerator',
			'wikibase.ValueViewBuilder',
			'wikibase.view.ToolbarFactory',
			'wikibase.view.ToolbarViewController',
			'wikibase.view.ViewController',
			'wikibase.view.ViewFactory',
			'wikibase.view.ViewFactoryFactory',
			'wikibase.WikibaseContentLanguages',
		],
	],
];
