<template>
	<div
		class="wikibase-wbui2025-snak-value"
		:data-snak-hash="snak.hash"
		:class="snakValueClass"
		v-html="snakValueHtml( snak )"
	></div>
</template>

<script>
const { defineComponent } = require( 'vue' );
const { snakValueHtml } = require( './store/serverRenderedHtml.js' );

// @vue/component
module.exports = exports = defineComponent( {
	name: 'WikibaseWbui2025SnakValue',
	props: {
		snak: {
			type: Object,
			required: true
		}
	},
	setup() {
		return {
			snakValueHtml
		};
	},
	computed: {
		snakValueClass() {
			return {
				'wikibase-wbui2025-media-value': this.snak.datatype === 'commonsMedia',
				'wikibase-wbui2025-time-value': this.snak.datatype === 'time',
				'wikibase-wbui2025-globe-coordinate-value': this.snak.datatype === 'globe-coordinate'
			};
		}
	},
	mounted() {
		if ( this.snak.datatype === 'globe-coordinate' ) {
			// Modelled off the inline js code that generated by CachingKartographerEmbeddinghandler::getMapframeInitJS()
			// and added to preview maps in CachingKartographerEmbeddinghandler::getPreviewHtml()
			mw.loader.using( 'ext.kartographer.frame' ).then( () => {
				const element = $( this.$el ).find( '.mw-kartographer-map[data-mw-kartographer]' );
				require( 'ext.kartographer.frame' ).initMapframeFromElement( element );
			} );
		}
	}
} );
</script>
