<template>
	<div
		class="wikibase-wbui2025-snak-value"
		:data-snak-hash="snak.hash"
		:class="snakValueClass"
	>
		<span class="snakValue" v-html="snakValueHtmlForHash( snak.hash )"></span>
		<span
			ref="snakAnchor"
			class="indicators"
			@click="togglePopover"
			v-html="indicatorsHtml"
		></span>
		<wbui2025-indicator-popover
			v-if="popoverVisible"
			:snak-hash="snak.hash"
			:anchor="$refs.snakAnchor"
			@close="popoverVisible = false"
		>
		</wbui2025-indicator-popover>
	</div>
</template>

<script>
const { defineComponent } = require( 'vue' );
const wbui2025 = require( 'wikibase.wbui2025.lib' );
const Wbui2025IndicatorPopover = require( './indicatorPopover.vue' );

// @vue/component
module.exports = exports = defineComponent( {
	name: 'WikibaseWbui2025SnakValue',
	components: {
		Wbui2025IndicatorPopover
	},
	props: {
		snak: {
			type: Object,
			required: true
		}
	},
	data() {
		return {
			popoverVisible: false
		};
	},
	computed: {
		snakValueClass() {
			return {
				'wikibase-wbui2025-media-value': this.snak.datatype === 'commonsMedia',
				'wikibase-wbui2025-time-value': this.snak.datatype === 'time',
				'wikibase-wbui2025-globe-coordinate-value': this.snak.datatype === 'globe-coordinate',
				'wikibase-wbui2025-tabular-data-value': this.snak.datatype === 'tabular-data',
				'wikibase-wbui2025-geo-shape-value': this.snak.datatype === 'geo-shape',
				'wikibase-wbui2025-musical-notation-value': this.snak.datatype === 'musical-notation'
			};
		},
		indicatorsHtml() {
			return wbui2025.store.getIndicatorsHtmlForSnakHash( this.snak.hash );
		}
	},
	methods: {
		snakValueHtmlForHash: wbui2025.store.snakValueHtmlForHash,
		togglePopover() {
			this.popoverVisible = !this.popoverVisible;
		}
	},
	mounted() {
		if ( this.snak.datatype === 'globe-coordinate' ) {
			// Modelled off the inline js code that generated by CachingKartographerEmbeddinghandler::getMapframeInitJS()
			// and added to preview maps in CachingKartographerEmbeddinghandler::getPreviewHtml()
			mw.loader.using( 'ext.kartographer.frame' ).then( () => {
				const element = $( this.$el ).find( '.mw-kartographer-map[data-mw-kartographer]' );
				require( 'ext.kartographer.frame' ).initMapframeFromElement( element );
			} );
		}
	}
} );
</script>
