<?php
// This file is generated by build/generateAutoload.php, do not adjust manually
// phpcs:disable Generic.Files.LineLength
global $wgAutoloadClasses;

$wgAutoloadClasses += [
	'Wikibase\\View\\DummyLocalizedTextProvider' => __DIR__ . '/src/DummyLocalizedTextProvider.php',
	'Wikibase\\View\\EditSectionGenerator' => __DIR__ . '/src/EditSectionGenerator.php',
	'Wikibase\\View\\EntityIdFormatterFactory' => __DIR__ . '/src/EntityIdFormatterFactory.php',
	'Wikibase\\View\\EntityTermsView' => __DIR__ . '/src/EntityTermsView.php',
	'Wikibase\\View\\EntityView' => __DIR__ . '/src/EntityView.php',
	'Wikibase\\View\\HtmlSnakFormatterFactory' => __DIR__ . '/src/HtmlSnakFormatterFactory.php',
	'Wikibase\\View\\HtmlTermRenderer' => __DIR__ . '/src/HtmlTermRenderer.php',
	'Wikibase\\View\\ItemView' => __DIR__ . '/src/ItemView.php',
	'Wikibase\\View\\LanguageDirectionalityLookup' => __DIR__ . '/src/LanguageDirectionalityLookup.php',
	'Wikibase\\View\\LocalizedTextProvider' => __DIR__ . '/src/LocalizedTextProvider.php',
	'Wikibase\\View\\Module\\TemplateModule' => __DIR__ . '/src/Module/TemplateModule.php',
	'Wikibase\\View\\PropertyView' => __DIR__ . '/src/PropertyView.php',
	'Wikibase\\View\\SimpleEntityTermsView' => __DIR__ . '/src/SimpleEntityTermsView.php',
	'Wikibase\\View\\SiteLinksView' => __DIR__ . '/src/SiteLinksView.php',
	'Wikibase\\View\\SnakHtmlGenerator' => __DIR__ . '/src/SnakHtmlGenerator.php',
	'Wikibase\\View\\SpecialPageLinker' => __DIR__ . '/src/SpecialPageLinker.php',
	'Wikibase\\View\\StatementGroupListView' => __DIR__ . '/src/StatementGroupListView.php',
	'Wikibase\\View\\StatementHtmlGenerator' => __DIR__ . '/src/StatementHtmlGenerator.php',
	'Wikibase\\View\\StatementSectionsView' => __DIR__ . '/src/StatementSectionsView.php',
	'Wikibase\\View\\Template\\Template' => __DIR__ . '/src/Template/Template.php',
	'Wikibase\\View\\Template\\TemplateFactory' => __DIR__ . '/src/Template/TemplateFactory.php',
	'Wikibase\\View\\Template\\TemplateRegistry' => __DIR__ . '/src/Template/TemplateRegistry.php',
	'Wikibase\\View\\TermsListView' => __DIR__ . '/src/TermsListView.php',
	'Wikibase\\View\\Tests\\EntityViewTestCase' => __DIR__ . '/tests/phpunit/EntityViewTestCase.php',
	'Wikibase\\View\\ToolbarEditSectionGenerator' => __DIR__ . '/src/ToolbarEditSectionGenerator.php',
	'Wikibase\\View\\ViewFactory' => __DIR__ . '/src/ViewFactory.php',
];
